sosmon/config/routes.rb
Sosmon::Application.routes.draw do
  resources :tests
  resources :services
  resources :clients

end

sosmon/app/models/client.rb
class Client < ActiveRecord::Base
  has_many :services
  attr_accessible :name

  alias_attribute :to_s, :name
end

sosmon/app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :client
  has_many :tests
  attr_accessible :desc, :name, :portfolio, :tags

  alias_attribute :to_s, :name
end

sosmon/app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :service
  attr_accessible :check_url, :enabled, :name, :opmode, :status, :tags, :uuid
end

sosmon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

sosmon/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, :notice => 'Client was successfully created.' }
        format.json { render :json => @client, :status => :created, :location => @client }
      else
        format.html { render :action => "new" }
        format.json { render :json => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, :notice => 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

sosmon/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    unless params[:client].blank?
      @services = Client.find(params[:client]).services
    else
      @services = Service.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    client = Client.find(params[:client])
    @service = client.services.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, :notice => 'Service was successfully created.' }
        format.json { render :json => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.json { render :json => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @service, :notice => 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end
end

sosmon/app/controllers/tests_controller.rb
class TestsController < ApplicationController
  # GET /tests
  # GET /tests.json
  def index
    unless params[:service].blank?
      @tests = Service.find(params[:service]).tests
    else
      @tests = Test.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tests }
    end
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
    @test = Test.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @test }
    end
  end

  # GET /tests/new
  # GET /tests/new.json
  def new
    @test = Test.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @test }
    end
  end

  # GET /tests/1/edit
  def edit
    @test = Test.find(params[:id])
  end

  # POST /tests
  # POST /tests.json
  def create
    service = Service.find(params[:service])
    @test = service.tests.new(params[:test])

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, :notice => 'Test was successfully created.' }
        format.json { render :json => @test, :status => :created, :location => @test }
      else
        format.html { render :action => "new" }
        format.json { render :json => @test.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tests/1
  # PUT /tests/1.json
  def update
    @test = Test.find(params[:id])

    respond_to do |format|
      if @test.update_attributes(params[:test])
        format.html { redirect_to @test, :notice => 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @test.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test = Test.find(params[:id])
    @test.destroy

    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end
end

sosmon/app/helpers/application_helper.rb
module ApplicationHelper
end

sosmon/app/helpers/clients_helper.rb
module ClientsHelper
end

sosmon/app/helpers/services_helper.rb
module ServicesHelper
end

sosmon/app/helpers/tests_helper.rb
module TestsHelper
end

sosmon/app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="label"><%= f.label :name %></span>
    <span class="input"><%= f.text_field :name %></span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sosmon/app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

sosmon/app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

sosmon/app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

sosmon/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>


<%= link_to 'Services', services_path(:client => @client.id) %> |
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

sosmon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sosmon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

sosmon/app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="label"><%= f.label :name %></span>
    <span class="input"><%= f.text_field :name %></span>
  </div>
  <div class="field">
    <span class="label"><%= f.label :portfolio %></span>
    <span class="input"><%= f.text_field :portfolio %></span>
  </div>
  <div class="field">
    <span class="label"><%= f.label :tags %></span>
    <span class="input"><%= f.text_field :tags %></span>
  </div>
  <div class="field">
    <span class="label"><%= f.label :client %></span>
    <span class="select"><%=
    select_tag(:client, options_from_collection_for_select(Client.all,
                                                           :id,
                                                           :name)) %></span>
  </div>
  <div class="field">
    <span class="label"><%= f.label :desc %></span>
    <span class="input"><%= f.text_area :desc %></span>
  </div>
  <div class="actions">
    <span class="button"><%= f.submit %></span>
  </div>
<% end %>

sosmon/app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

sosmon/app/views/services/index.html.erb
<h1>Listing services</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Portfolio</th>
    <th>Tags</th>
    <th>Client</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @services.each do |service| %>
  <tr>
    <td><%= service.name %></td>
    <td><%= service.portfolio %></td>
    <td><%= service.tags %></td>
    <td><%= service.client %></td>
    <td><%= service.desc %></td>
    <td><%= link_to 'Show', service %></td>
    <td><%= link_to 'Edit', edit_service_path(service) %></td>
    <td><%= link_to 'Destroy', service, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service', new_service_path %>

sosmon/app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

sosmon/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @service.name %>
</p>

<p>
  <b>Portfolio:</b>
  <%= @service.portfolio %>
</p>

<p>
  <b>Tags:</b>
  <%= @service.tags %>
</p>

<p>
  <b>Client:</b>
  <%= @service.client %>
</p>

<p>
  <b>Desc:</b>
  <%= @service.desc %>
</p>


<%= link_to 'Tests', tests_path(:service => @service.id) %> |
<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>